model:
  decoder:
    type: Transformer
    n_layers: 1
    n_heads: 16
    mlp_ratio: 4

  masker:
    type: Masker
    decoder:
      type: GDecoder
      double: true
      n_layers: 2
      kernel_size: 3
      act: gelu
      norm: ln
      text: false

    sim2mask:
      init_w: 10.0
      init_b: 0
      gumbel_tau: 1.0
      learnable_w: true
      learnable_b: false
      learnable: false
      scale: 10.0
      ratio: 0.0
      
evaluate:
  bg_thresh: 0.4
  clip_w: 0.3
  scale: 10
  bias: -2.5

  eval_only: true
  template: simple 
  task:
    # - imagenets50
    # - imagenets300
    # - imagenets919
    # - voc
    # - context
    # - coco_object
    # - coco_stuff
    # - context59
    - voc20
    # - cityscapes
    # - ade20k

  # training splits
  t_voc20: segmentation/configs/_base_/datasets/t_pascal_voc12_20.py
  t_context59: segmentation/configs/_base_/datasets/t_pascal_context59.py

  # evaluation
  voc: segmentation/configs/_base_/datasets/pascal_voc12.py
  voc20: segmentation/configs/_base_/datasets/pascal_voc12_20.py
  context: segmentation/configs/_base_/datasets/pascal_context.py
  context59: segmentation/configs/_base_/datasets/pascal_context59.py
  coco_stuff: segmentation/configs/_base_/datasets/stuff.py
  coco_object: segmentation/configs/_base_/datasets/coco.py
  cityscapes: segmentation/configs/_base_/datasets/cityscapes.py
  ade20k: segmentation/configs/_base_/datasets/ade20k.py
  imagenets50: segmentation/configs/_base_/datasets/imagenets50.py
  imagenets300: segmentation/configs/_base_/datasets/imagenets300.py
  imagenets919: segmentation/configs/_base_/datasets/imagenets919.py
